In [ ]:
import pandas as pd
lista_nombres=["alexander","alejandra","dario"]
lista_pesos=[69,57,64]#peso en kg
lista_alturas=[1.78,1.6,1.64] #altura en m

dicc_datos= {"nombres":lista_nombres,"pesos":lista_pesos,"alturas":lista_alturas}
df=pd.DataFrame(dicc_datos) #convierte al diccionario en un dataframe(marco de datos o tabla o dataset)
df

     nombres  pesos  alturas
0  alexander     69     1.78
1  alejandra     57     1.60
2      dario     64     1.64

In [ ]:
import pandas as pd
lista_nombres=["alexander","alejandra","dario","geovany","ana","santiago","rita","jaime","fernando","rodrigo","mentor","ejecutor"]
lista_pesos=[69,57,64,65,62,65,90,68,72,65,74,78]#peso en kg
lista_alturas=[1.78,1.60,1.64,1.70,1.57,1.62,1.63,1.65,1.72,1.68,1.71,1.78] #altura en m

dicc_datos={"nombres":lista_nombres,"pesos":lista_pesos,"alturas":lista_alturas}
df=pd.DataFrame(dicc_datos) #convierte al diccionario en un dataframe(marco de datos o tabla o dataset)
df

      nombres  pesos  alturas
0   alexander     69     1.78
1   alejandra     57     1.60
2       dario     64     1.64
3     geovany     65     1.70
4         ana     62     1.57
5    santiago     65     1.62
6        rita     90     1.63
7       jaime     68     1.65
8    fernando     72     1.72
9     rodrigo     65     1.68
10     mentor     74     1.71
11   ejecutor     78     1.78

In [ ]:
df["imc"] = df["pesos"] / (df["alturas"]**2)
df

      nombres  pesos  alturas        imc
0   alexander     69     1.78  21.777553
1   alejandra     57     1.60  22.265625
2       dario     64     1.64  23.795360
3     geovany     65     1.70  22.491349
4         ana     62     1.57  25.153150
5    santiago     65     1.62  24.767566
6        rita     90     1.63  33.874064
7       jaime     68     1.65  24.977043
8    fernando     72     1.72  24.337480
9     rodrigo     65     1.68  23.030045
10     mentor     74     1.71  25.306932
11   ejecutor     78     1.78  24.618104

In [ ]:
import pandas as pd
lista_nombres=["alexander","alejandra","dario","geovany","ana","santiago","rita","jaime","fernando","rodrigo","mentor","ejecutor"]
lista_pesos=[69,57,64,65,62,65,90,68,72,65,74,78]#peso en kg
lista_alturas=[1.78,1.60,1.64,1.70,1.57,1.62,1.63,1.65,1.72,1.68,1.71,1.78] #altura en m

dicc_datos={"nombres":lista_nombres,"pesos":lista_pesos,"alturas":lista_alturas}
df=pd.DataFrame(dicc_datos) #convierte al diccionario en un dataframe(marco de datos o tabla o dataset)
df["imc"] = df["pesos"] / (df["alturas"]**2)
def clasificacion(imc):
    if imc < 18.5:
        return "bajo peso"
    elif imc< 25:
        return "peso normal"
    else:
      return "sobrepeso"
df["clasificacion"] = df["imc"].apply(clasificacion)
df

      nombres  pesos  alturas        imc clasificacion
0   alexander     69     1.78  21.777553   peso normal
1   alejandra     57     1.60  22.265625   peso normal
2       dario     64     1.64  23.795360   peso normal
3     geovany     65     1.70  22.491349   peso normal
4         ana     62     1.57  25.153150     sobrepeso
5    santiago     65     1.62  24.767566   peso normal
6        rita     90     1.63  33.874064     sobrepeso
7       jaime     68     1.65  24.977043   peso normal
8    fernando     72     1.72  24.337480   peso normal
9     rodrigo     65     1.68  23.030045   peso normal
10     mentor     74     1.71  25.306932     sobrepeso
11   ejecutor     78     1.78  24.618104   peso normal