In [48]:
import pandas as pd
import numpy as np
listay=[78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4]
listax1=[7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10]
listax2=[26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68]
listax3=[ 6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8]
listax4=[60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 6]





dicc_datos={"y":listay,"x1":listax1,"x2":listax2,"x3":listax3,"x4":listax4}

df=pd.DataFrame(dicc_datos)

print("orginal dataframe:")
display(df)
# replace the "y" column values  with ones
df["y"]=1

print("\nDataFrame with 'y' column converted to ones:")
display(df)
#pasamos la tabla a matriz
matrix_df=df.values
display(matrix_df)

orginal dataframe:

        y  x1  x2  x3  x4
0    78.5   7  26   6  60
1    74.3   1  29  15  52
2   104.3  11  56   8  20
3    87.6  11  31   8  47
4    95.9   7  52   6  33
5   109.2  11  55   9  22
6   102.7   3  71  17   6
7    72.5   1  31  22  44
8    93.1   2  54  18  22
9   115.9  21  47   4  26
10   83.8   1  40  23  34
11  113.3  11  66   9  12
12  109.4  10  68   8   6

DataFrame with 'y' column converted to ones:

    y  x1  x2  x3  x4
0   1   7  26   6  60
1   1   1  29  15  52
2   1  11  56   8  20
3   1  11  31   8  47
4   1   7  52   6  33
5   1  11  55   9  22
6   1   3  71  17   6
7   1   1  31  22  44
8   1   2  54  18  22
9   1  21  47   4  26
10  1   1  40  23  34
11  1  11  66   9  12
12  1  10  68   8   6

array([[ 1,  7, 26,  6, 60],
       [ 1,  1, 29, 15, 52],
       [ 1, 11, 56,  8, 20],
       [ 1, 11, 31,  8, 47],
       [ 1,  7, 52,  6, 33],
       [ 1, 11, 55,  9, 22],
       [ 1,  3, 71, 17,  6],
       [ 1,  1, 31, 22, 44],
       [ 1,  2, 54, 18, 22],
       [ 1, 21, 47,  4, 26],
       [ 1,  1, 40, 23, 34],
       [ 1, 11, 66,  9, 12],
       [ 1, 10, 68,  8,  6]])

In [49]:
matrixt=matrix_df.T
display(matrixt)

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 7,  1, 11, 11,  7, 11,  3,  1,  2, 21,  1, 11, 10],
       [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68],
       [ 6, 15,  8,  8,  6,  9, 17, 22, 18,  4, 23,  9,  8],
       [60, 52, 20, 47, 33, 22,  6, 44, 22, 26, 34, 12,  6]])

In [60]:
matrix_y=df_from_first_table[["y"]].values
display(matrix_y)

NameError: name 'df_from_first_table' is not defined